import { StyleSheet } from "react-native";

export const myProfileStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  header: {
    backgroundColor: "#8B5CF6",
    paddingTop: 20,
    paddingBottom: 30,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginLeft: 12,
  },
  backButton: {
    position: "absolute",
    left: 20,
    top: 20,
    padding: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  profileImageContainer: {
    position: "relative",
    marginBottom: 15,
  },
  profileImagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  profileImageText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#8B5CF6",
  },
  userName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 5,
  },
  userRole: {
    fontSize: 16,
    color: "#E5E7EB",
    marginBottom: 15,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  statLabel: {
    fontSize: 14,
    color: "#E5E7EB",
  },
  profileInfo: {
    backgroundColor: "#FFFFFF",
    margin: 20,
    padding: 20,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  infoItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  infoText: {
    marginLeft: 15,
    fontSize: 16,
    color: "#374151",
    flex: 1,
  },
  section: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#374151",
    marginBottom: 15,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionSubtitle: {
    fontSize: 12,
    color: "#6B7280",
  },
  sectionHelperText: {
    fontSize: 12,
    color: "#9CA3AF",
    marginBottom: 12,
  },
  sectionHeaderActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionLink: {
    fontSize: 14,
    color: "#8B5CF6",
    fontWeight: "600",
  },
  subjectItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  subjectInfo: {
    flex: 1,
  },
  subjectName: {
    fontSize: 16,
    color: "#374151",
  },
  subjectLevel: {
    fontSize: 14,
    color: "#8B5CF6",
    fontWeight: "500",
    textTransform: "capitalize",
  },
  subjectRate: {
    fontSize: 16,
    color: "#10B981",
    fontWeight: "600",
  },
  lessonItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  lessonItemLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  lessonHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  lessonTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    marginRight: 12,
  },
  lessonStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  lessonStatusBadgeActive: {
    backgroundColor: "#DCFCE7",
  },
  lessonStatusBadgeInactive: {
    backgroundColor: "#FEE2E2",
  },
  lessonStatusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  lessonStatusTextActive: {
    color: "#047857",
  },
  lessonStatusTextInactive: {
    color: "#B91C1C",
  },
  lessonSubject: {
    fontSize: 15,
    color: "#4B5563",
    marginBottom: 4,
  },
  lessonSchedule: {
    fontSize: 14,
    color: "#4B5563",
    marginBottom: 4,
  },
  lessonMeta: {
    fontSize: 13,
    color: "#6B7280",
    marginBottom: 4,
  },
  lessonEmptyContainer: {
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 12,
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  lessonEmptyIcon: {
    marginBottom: 8,
  },
  lessonEmptyTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#4B5563",
    marginBottom: 4,
  },
  lessonEmptySubtitle: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 18,
  },
  paymentSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  paymentCard: {
    flex: 1,
    backgroundColor: "#EEF2FF",
    padding: 16,
    borderRadius: 12,
  },
  paymentCardPaid: {
    backgroundColor: "#ECFDF5",
  },
  paymentCardPending: {
    backgroundColor: "#FEF3C7",
  },
  paymentCardLabel: {
    fontSize: 13,
    color: "#6B7280",
    marginBottom: 8,
  },
  paymentCardAmount: {
    fontSize: 20,
    fontWeight: "700",
    color: "#111827",
  },
  paymentCardCount: {
    fontSize: 12,
    color: "#6B7280",
    marginTop: 8,
  },
  monthFilterContainer: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    marginLeft: 12,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 4,
    minWidth: 150,
    position: "relative",
  },
  monthFilterValue: {
    flex: 1,
    fontSize: 14,
    color: "#111827",
  },
  monthFilterIcon: {
    marginLeft: 8,
    color: "#6B7280",
  },
  monthPickerNative: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0,
    width: "100%",
    height: "100%",
  },
  paymentList: {
    gap: 12,
  },
  paymentItem: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 16,
    backgroundColor: "#FFFFFF",
  },
  paymentItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  paymentItemTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    flex: 1,
    marginRight: 12,
  },
  paymentStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  paymentStatusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  paymentStatusPaid: {
    backgroundColor: "#DCFCE7",
  },
  paymentStatusPending: {
    backgroundColor: "#FEF3C7",
  },
  paymentStatusTextPaid: {
    color: "#047857",
  },
  paymentStatusTextPending: {
    color: "#B45309",
  },
  paymentAmount: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 8,
  },
  paymentMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  paymentMetaIcon: {
    marginRight: 6,
  },
  paymentMetaText: {
    fontSize: 13,
    color: "#6B7280",
  },
  errorLink: {
    fontSize: 12,
    color: "#DC2626",
    fontWeight: "600",
  },
  centeredState: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 20,
  },
  attendanceItem: {
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    backgroundColor: "#FFFFFF",
  },
  attendanceItemHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  attendanceItemInfo: {
    flex: 1,
    marginRight: 12,
  },
  attendanceItemDate: {
    fontSize: 16,
    fontWeight: "600",
    color: "#111827",
    marginBottom: 4,
  },
  attendanceMeta: {
    fontSize: 13,
    color: "#6B7280",
    marginBottom: 4,
  },
  attendanceStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  attendanceStatusText: {
    fontSize: 12,
    fontWeight: "600",
  },
  attendanceStatusAttended: {
    backgroundColor: "#DCFCE7",
  },
  attendanceStatusTextAttended: {
    color: "#047857",
  },
  attendanceStatusPending: {
    backgroundColor: "#FEF3C7",
  },
  attendanceStatusTextPending: {
    color: "#B45309",
  },
  attendanceStatusUpcoming: {
    backgroundColor: "#DBEAFE",
  },
  attendanceStatusTextUpcoming: {
    color: "#1D4ED8",
  },
  attendanceStatusMissed: {
    backgroundColor: "#FEE2E2",
  },
  attendanceStatusTextMissed: {
    color: "#B91C1C",
  },
  attendanceMarkButton: {
    marginTop: 12,
    backgroundColor: "#8B5CF6",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  attendanceMarkButtonDisabled: {
    backgroundColor: "#A78BFA",
  },
  attendanceMarkButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  menuContainer: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 12,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  menuText: {
    flex: 1,
    marginLeft: 15,
    fontSize: 16,
    color: "#374151",
  },
  demoButton: {
    backgroundColor: "#F59E0B",
    marginHorizontal: 20,
    marginBottom: 10,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  demoButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  logoutButton: {
    backgroundColor: "#EF4444",
    marginHorizontal: 20,
    marginBottom: 30,
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
  },
  logoutText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
