import { StyleSheet } from "react-native";

export const tutorProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  centerContent: {
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 18,
    color: "#6B7280",
  },
  errorText: {
    fontSize: 18,
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 20,
  },
  errorBanner: {
    backgroundColor: "#FEF3C7",
    padding: 10,
    marginHorizontal: 20,
    marginTop: 10,
    borderRadius: 8,
  },
  errorBannerText: {
    color: "#92400E",
    fontSize: 14,
    textAlign: "center",
  },
  header: {
    backgroundColor: "#8B5CF6",
    paddingTop: 44,
    paddingBottom: 16,
    paddingHorizontal: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  refreshButton: {
    padding: 8,
  },
  content: {
    flex: 1,
  },
  profileCard: {
    backgroundColor: "#8B5CF6",
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    padding: 20,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileImageContainer: {
    position: "relative",
    marginRight: 20,
  },
  profileImagePlaceholder: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
  },
  profileImageText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#8B5CF6",
  },
  profileInfo: {
    flex: 1,
  },
  tutorName: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  subjectAndAge: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  primarySubject: {
    fontSize: 16,
    color: "#E5E7EB",
    marginRight: 16,
  },
  age: {
    fontSize: 16,
    color: "#E5E7EB",
  },
  contactInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  phoneNumber: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  section: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 12,
    padding: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#374151",
    marginBottom: 12,
  },
  sectionText: {
    fontSize: 16,
    color: "#6B7280",
    lineHeight: 24,
  },
  subjectMainInfo: {
    flex: 1,
  },
  subjectName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
  },
  subjectGrade: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 2,
  },
  subjectDetails: {
    alignItems: "flex-end",
  },
  subjectLevel: {
    fontSize: 14,
    color: "#8B5CF6",
    fontWeight: "500",
    backgroundColor: "#EDE9FE",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 4,
  },
  subjectRate: {
    fontSize: 16,
    color: "#10B981",
    fontWeight: "600",
  },
  noSubjects: {
    fontSize: 16,
    color: "#9CA3AF",
    fontStyle: "italic",
  },
  // Accordion styles
  subjectAccordion: {
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    overflow: "hidden",
  },
  subjectHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    backgroundColor: "#FAFAFA",
  },
  subjectHeaderLeft: {
    flex: 1,
    marginRight: 12,
  },
  lessonsContainer: {
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  lessonCard: {
    backgroundColor: "#F9FAFB",
    padding: 16,
    borderRadius: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  lessonHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  lessonTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#374151",
    flex: 1,
  },
  lessonRate: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#F59E0B",
    marginLeft: 12,
  },
  lessonDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  lessonDetail: {
    fontSize: 14,
    color: "#6B7280",
    marginLeft: 8,
  },
  lessonDescription: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 8,
    fontStyle: "italic",
    lineHeight: 20,
  },
  enrollButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8B5CF6",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 12,
    gap: 8,
  },
  enrollButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  noLessonsContainer: {
    alignItems: "center",
    padding: 32,
  },
  noLessonsText: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 12,
    textAlign: "center",
  },
  ratingContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  ratingLeft: {
    flex: 1,
  },
  starsContainer: {
    flexDirection: "row",
    marginBottom: 4,
  },
  ratingText: {
    fontSize: 14,
    color: "#6B7280",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    marginHorizontal: 20,
    marginVertical: 20,
    gap: 12,
  },
  primaryButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#8B5CF6",
    paddingVertical: 14,
    borderRadius: 12,
    gap: 8,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
